### PR TITLE
close incoming channel explicitly

### PR DESCRIPTION
**Pull request by worxli**
closeChannel does not close it if there are no more messages in the
channel.

---
This change is [Reviewable](https://reviewable.io/reviews/anapaya/gobgp/1)

### CODE REVIEW

**Review by scrye — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/gobgp/1#-:-MbFySFX8UWujJEgS_xW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @worxli)

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/gobgp/1)* status: all files reviewed, 1 unresolved discussion (waiting on @worxli)

___
*[pkg/zebra/zapi.go, line 1469 at r1](https://reviewable.io/reviews/anapaya/gobgp/1#-MbG4J1q2g2LHScwCgb0:-MbG4J1q2g2LHScwCgb1:bgdi0t1) ([raw file](https://github.com/anapaya/gobgp/blob/3e758f637b370883a0a0d1390c26b08733cebd9c/pkg/zebra/zapi.go#L1469)):*
> ```Go
> 	// Start receive loop only when the first message successfully received.
> 	go func() {
> 		defer closeChannel(incoming)
> ```

simply change this to `defer close(incoming)`

There is no reason to do the `closeChannel` anti-pattern here.
We only close the channel from the writer side, which is good.

You can drop the line you changed again.

Also, I think we should try to upstream this change eventually

**Review by scrye — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/gobgp/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Oncilla)

___
*[pkg/zebra/zapi.go, line 1469 at r1](https://reviewable.io/reviews/anapaya/gobgp/1#-MbG4J1q2g2LHScwCgb0:-MbG5Q0xAw1J8Sl5fygi:b-luvmcd) ([raw file](https://github.com/anapaya/gobgp/blob/3e758f637b370883a0a0d1390c26b08733cebd9c/pkg/zebra/zapi.go#L1469)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

simply change this to `defer close(incoming)`

There is no reason to do the `closeChannel` anti-pattern here.
We only close the channel from the writer side, which is good.

You can drop the line you changed again.

Also, I think we should try to upstream this change eventually





</blockquote></details>

I agree 100%.

`closeChannel` is anyway a completely broken method. The less calls to it, the better.

**Review by worxli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/gobgp/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Oncilla and @scrye)

___
*[pkg/zebra/zapi.go, line 1469 at r1](https://reviewable.io/reviews/anapaya/gobgp/1#-MbG4J1q2g2LHScwCgb0:-MbGAAo22S6zH48ZHVAj:b-896fix) ([raw file](https://github.com/anapaya/gobgp/blob/3e758f637b370883a0a0d1390c26b08733cebd9c/pkg/zebra/zapi.go#L1469)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

I agree 100%.

`closeChannel` is anyway a completely broken method. The less calls to it, the better.
</blockquote></details>

Done.

**Review by oncilla — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/gobgp/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @worxli)

**Pull request merged**
